name: Build and Publish .NET Project

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    strategy: 
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
        include:
          - os: "ubuntu-latest"
            runtime: "linux-x64"
          - os: "windows-latest"
            runtime: "win-x64"
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1
        
      - name: Setup Dotnet SDK
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '10.0.x'
          
      - name: Restore .NET Project
        run: dotnet restore -r ${{ matrix.runtime }}
        
      - name: Publish .NET Project for ${{ matrix.runtime }}
        run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained --no-restore -o ./publish/VuzScrapper-${{ matrix.runtime }}
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VuzScrapper-${{ matrix.runtime }}
          path: ./publish/VuzScrapper-${{ matrix.runtime }}
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1
          
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: 
          path: ./artifacts
      
      - name: Archive Linux Artifacts
        run: tar -cf ./artifacts/VuzScrapper-linux-x64.tar ./artifacts/VuzScrapper-linux-x64/* && gzip ./artifacts/VuzScrapper-linux-x64.tar -9
        
      - name: Archive Windows Artifacts
        run: zip -r ./artifacts/VuzScrapper-win-x64.zip ./artifacts/VuzScrapper-win-x64/* -9

      - name: List Files
        run: ls -R ./artifacts
        
      - name: Publish Releases
        uses: softprops/action-gh-release@v2
        with:
          name: Release (${{ github.ref_name }})
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            ./artifacts/VuzScrapper-linux-x64.tar.gz
            ./artifacts/VuzScrapper-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}